version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: donsang_db_laravel
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - certification

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: donsang_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - certification

    # laravel apache project container
    www:
        build: docker/php
        container_name: donsang_apache
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - certification

networks:
    certification:

volumes:
    db-data: